"""Unit tests for `pools.constant_product`. Expected outputs are independently
hand-computed against the documented `UniswapV2Library.getAmountOut` formula
(module docstring in `pools/constant_product.py`) via long division worked out in
each comment below -- not generated by calling the function under test (per
issue guidance: correctness fixtures must not be self-referential).
"""

from __future__ import annotations

import pytest

from pools.constant_product import QuoteStatus, get_amount_out, quote_exact_in
from snapshot.models import ConstantProductPoolState


def test_get_amount_out_hand_computed_with_fee() -> None:
    # amount_in=100, reserve_in=1000, reserve_out=2000, fee_bps=30 (0.3%).
    # amountInWithFee = 100 * (10000-30) = 100 * 9970 = 997,000
    # numerator        = 997,000 * 2000 = 1,994,000,000
    # denominator       = 1000*10000 + 997,000 = 10,000,000 + 997,000 = 10,997,000
    # amountOut = floor(1,994,000,000 / 10,997,000)
    #   10,997,000 * 181 = 1,990,457,000  (<= numerator)
    #   10,997,000 * 182 = 2,001,454,000  (>  numerator)
    #   => floor = 181
    assert get_amount_out(100, 1000, 2000, fee_bps=30) == 181


def test_get_amount_out_hand_computed_zero_fee() -> None:
    # With fee_bps=0 the general formula collapses to the textbook zero-fee
    # constant-product quote amountOut = floor(amountIn*reserveOut /
    # (reserveIn+amountIn)) -- a second, independently-stated formula used only
    # as a cross-check for this vector:
    # amount_in=50, reserve_in=500, reserve_out=1000
    # amountOut = floor(50*1000 / (500+50)) = floor(50,000/550) = floor(90.909..) = 90
    #   550 * 90 = 49,500 (<= 50,000); 550 * 91 = 50,050 (> 50,000) => floor = 90
    assert get_amount_out(50, 500, 1000, fee_bps=0) == 90


def test_get_amount_out_larger_vector() -> None:
    # amount_in=100_000, reserve_in=1_000_000, reserve_out=3_000_000, fee_bps=30
    # amountInWithFee = 100_000 * 9970 = 997,000,000
    # numerator = 997,000,000 * 3,000,000 = 2,991,000,000,000,000
    # denominator = 1,000,000*10000 + 997,000,000 = 10,000,000,000 + 997,000,000
    #             = 10,997,000,000
    # amountOut = floor(2,991,000,000,000,000 / 10,997,000,000)
    #   10,997,000,000 * 271,983 = 2,990,998,551,000,000 (<= numerator)
    #   10,997,000,000 * 271,984 = 2,991,009,548,000,000 (>  numerator)
    #   => floor = 271,983
    assert get_amount_out(100_000, 1_000_000, 3_000_000, fee_bps=30) == 271_983


def test_get_amount_out_rejects_non_positive_amount_in() -> None:
    with pytest.raises(ValueError):
        get_amount_out(0, 1000, 2000, fee_bps=30)
    with pytest.raises(ValueError):
        get_amount_out(-1, 1000, 2000, fee_bps=30)


def test_get_amount_out_rejects_empty_reserves() -> None:
    with pytest.raises(ValueError):
        get_amount_out(100, 0, 2000, fee_bps=30)
    with pytest.raises(ValueError):
        get_amount_out(100, 1000, 0, fee_bps=30)


POOL = ConstantProductPoolState(
    pool_id="p", token0="TKA", token1="TKB", reserve0=1000, reserve1=2000, fee_bps=30
)


def test_quote_exact_in_ok_matches_get_amount_out_and_updates_reserves() -> None:
    result = quote_exact_in(POOL, "TKA", 100)
    assert result.status is QuoteStatus.OK
    assert result.amount_out == 181  # see test_get_amount_out_hand_computed_with_fee
    assert result.amount_in_consumed == 100
    assert result.new_state is not None
    assert result.new_state.reserve0 == 1000 + 100
    assert result.new_state.reserve1 == 2000 - 181
    # quote_exact_in never mutates the input state.
    assert POOL.reserve0 == 1000
    assert POOL.reserve1 == 2000


def test_quote_exact_in_direction_token1_in() -> None:
    result = quote_exact_in(POOL, "TKB", 200)
    # amount_in=200, reserve_in=2000 (token1), reserve_out=1000 (token0), fee=30
    # amountInWithFee = 200*9970 = 1,994,000
    # numerator = 1,994,000*1000 = 1,994,000,000
    # denominator = 2000*10000 + 1,994,000 = 20,000,000+1,994,000 = 21,994,000
    # amountOut = floor(1,994,000,000 / 21,994,000)
    #   21,994,000*90 = 1,979,460,000 (<= numerator)
    #   21,994,000*91 = 2,001,454,000 (>  numerator) => floor = 90
    assert result.status is QuoteStatus.OK
    assert result.amount_out == 90
    assert result.new_state is not None
    assert result.new_state.reserve1 == 2000 + 200
    assert result.new_state.reserve0 == 1000 - 90


def test_quote_exact_in_unsupported_token() -> None:
    result = quote_exact_in(POOL, "TKZ", 100)
    assert result.status is QuoteStatus.UNSUPPORTED_TOKEN
    assert result.amount_out == 0
    assert result.new_state is None


def test_quote_exact_in_insufficient_liquidity_zero_reserve() -> None:
    empty_pool = ConstantProductPoolState(
        pool_id="p2", token0="TKA", token1="TKB", reserve0=0, reserve1=1000, fee_bps=30
    )
    result = quote_exact_in(empty_pool, "TKA", 100)
    assert result.status is QuoteStatus.INSUFFICIENT_LIQUIDITY
    assert result.amount_out == 0
    assert result.new_state is None


def test_quote_exact_in_insufficient_liquidity_rounds_to_zero_output() -> None:
    # A tiny amount_in against huge reserves rounds down to zero output --
    # distinct from "empty pool", but still a typed insufficient-liquidity
    # failure rather than a fabricated zero-output success.
    deep_pool = ConstantProductPoolState(
        pool_id="p3", token0="TKA", token1="TKB", reserve0=10**30, reserve1=10**30, fee_bps=30
    )
    result = quote_exact_in(deep_pool, "TKA", 1)
    assert result.status is QuoteStatus.INSUFFICIENT_LIQUIDITY
    assert result.amount_out == 0
    assert result.new_state is None


def test_quote_exact_in_rejects_non_positive_amount() -> None:
    with pytest.raises(ValueError):
        quote_exact_in(POOL, "TKA", 0)
    with pytest.raises(ValueError):
        quote_exact_in(POOL, "TKA", -5)


def test_two_sequential_swaps_thread_state_forward() -> None:
    # docs/DESIGN.md §2.3: "Test next-state correctness ... including two
    # sequential swaps through the same pool."
    first = quote_exact_in(POOL, "TKA", 100)
    assert first.new_state is not None
    second = quote_exact_in(first.new_state, "TKA", 100)
    assert second.status is QuoteStatus.OK
    assert second.new_state is not None
    # Second swap sees the reserves *after* the first swap, not the original pool.
    assert second.new_state.reserve0 == 1000 + 100 + 100
    assert second.new_state.reserve1 == 2000 - first.amount_out - second.amount_out
    # A second swap of equal input against a now-more-expensive pool yields
    # strictly less output than the first (constant-product price impact).
    assert second.amount_out < first.amount_out
