"""WHI-1633: the stage-L attempt history and the §8.6 yield of the valid units, as Markdown.

Presentation only. It reads the committed `timing-analysis.json` (written by `r024_campaign.py
analyze --stage L`) and the committed copy of the stage-L ledger, and renders what contract R024-C/1
§8.4 item 6 and §8.6 ask `results.md` to report. The frozen `tables` renderer prints only each
attempt's validity and triggers: per unit the launch-gate history, per attempt its window, T1/T2
monitoring and triggers, and per valid unit the descriptive medians (U1–U6) or the single-request
solve times and CLI wall times (UQ). This file was added after stage L (disclosed in `results.md`).
It decides nothing and changes no frozen analysis code. Its output is regenerated byte-identically
by `tests/research_024/test_r024_campaign.py`.

    uv run python tools/research_024/r024_timing_view.py <analysis.json> <ledger.jsonl> --out <md>
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections import Counter
from collections.abc import Mapping, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[2]
SCHEDULE = REPO / "config" / "research_024" / "campaign.yaml"


def _utc(t: float | None) -> str:
    return "–" if t is None else datetime.fromtimestamp(t, UTC).strftime("%m-%d %H:%M:%SZ")


def _dur(seconds: float | None) -> str:
    if seconds is None:
        return "–"
    s = round(seconds)
    return f"{s // 3600}h{s % 3600 // 60:02d}m{s % 60:02d}s"


def _s(v: float | None) -> str:
    return "–" if v is None else f"{v:.4f}"


def _mib(v: float | None) -> str:
    return "–" if v is None else f"{v / 2**20:.1f}"


def _table(head: Sequence[str], rows: Sequence[Sequence[Any]]) -> list[str]:
    out = ["| " + " | ".join(head) + " |", "|" + " --- |" * len(head)]
    out += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return out + [""]


def _gate_windows(ledger: Sequence[Mapping[str, Any]], unit: str) -> dict[int, dict[str, Any]]:
    """Per attempt number: launch-gate groups, failed groups, the first sample and the passing
    group's time (the launch wait), from the ledger's `launch_gate` entries."""
    out: dict[int, dict[str, Any]] = {}
    for e in ledger:
        if e.get("event") != "launch_gate" or e.get("unit") != unit:
            continue
        w = out.setdefault(
            int(e["attempt"]),
            {"groups": 0, "failed": 0, "first": e["samples"][0]["t"], "passed": None, "max": []},
        )
        w["groups"] += 1
        w["max"].append(e["max_load1"])
        if e["passed"]:
            w["passed"] = e["t"]
            w["passed_max"] = e["max_load1"]
        else:
            w["failed"] += 1
    return out


def _attempts(raw: Mapping[str, Any], a: Mapping[str, Any], ledger: Sequence[Any]) -> list[str]:
    rows = []
    for unit in (str(u["unit"]) for u in raw["timing"]["units"]):
        view = a["units"][unit]
        gates = _gate_windows(ledger, unit)
        for attempt, v in view["attempts"].items():
            k = int(attempt.rsplit("-a", 1)[1])
            g = gates.get(k, {})
            d = v.get("detail") or {}
            t1, t2 = d.get("T1") or {}, d.get("T2") or {}
            wait = None if g.get("passed") is None else g["passed"] - g["first"]
            rows.append(
                [
                    unit,
                    f"`{attempt}`",
                    f"{g.get('groups', 0)} ({g.get('failed', 0)} failed), "
                    f"wait {_dur(wait)}, passed at max {g.get('passed_max', 0):.2f}",
                    _utc(v.get("t_start")),
                    _utc(v.get("t_end")),
                    _dur((v.get("t_end") or 0) - (v.get("t_start") or 0)),
                    f"{t1.get('max_load1', 0):.2f} ({t1.get('over')} of {t1.get('samples')})",
                    f"{t2.get('max_gap_seconds', 0):.0f}",
                    f"{v.get('caffeinate_held')} / {v.get('pmset_captured')}",
                    ", ".join(v.get("triggers") or []) or "–",
                    "**valid**" if v.get("valid") else "invalid",
                ]
            )
        o = view["outcome"] or {}
        rows.append(
            [
                unit,
                "**outcome**",
                f"**{o.get('outcome')}**",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                f"selected `{o['attempt']}`" if o.get("attempt") else "none",
            ]
        )
    return [
        "## Attempts (§8.4)",
        "",
        "Launch gate: groups of five 30-s samples of the 1-min load, none above 3.0, re-sampled "
        "every 300 s; `wait` runs from the first sample of the attempt's launch window to the "
        "passing group. T1: max 1-min load in the window (samples above 5.0 of all samples). "
        "T2: largest sampling gap (s). T4: `caffeinate` held / `pmset` captured. Times UTC.",
        "",
        *_table(
            (
                "unit",
                "attempt",
                "launch gate groups",
                "start",
                "end",
                "window",
                "T1 max",
                "T2 gap",
                "T4",
                "triggers",
                "validity",
            ),
            rows,
        ),
    ]


def _med(stat: Mapping[str, Any] | None) -> float | None:
    return None if not stat else stat.get("median")


def _measured(name: str, y: Mapping[str, Any]) -> list[str]:
    load = y.get("load") or {}
    out = [
        f"### `{name}` (`{y['experiment']}`)",
        "",
        f"Runner load record: max 1-min load {load.get('max_loadavg_1m', 0):.2f} over "
        f"{load.get('samples')} samples, `contaminated` {load.get('contaminated')}. Medians over "
        "cases of each case's median (warm process, 5 repeats per order); noise = "
        "`|ln geomean(reverse/fixed)|`; seconds.",
        "",
    ]
    rows = []
    for label, block in y["timing"].items():
        for ident, v in block.items():
            rows.append(
                [
                    label,
                    f"`{ident}`",
                    v["case_median_wall_seconds"]["n"],
                    _s(_med(v["case_median_wall_seconds"])),
                    _s(_med(v["case_median_cpu_seconds"])),
                    _s(_med(v["prepare_seconds"])),
                    f"{v['noise_wall']['noise']:.3f}",
                    f"{v['noise_cpu']['noise']:.3f}",
                ]
            )
    out += _table(
        (
            "cohort / bundle",
            "identity",
            "cases",
            "warm wall p50",
            "warm CPU p50",
            "prepare p50",
            "noise wall",
            "noise CPU",
        ),
        rows,
    )
    rows = []
    for label, block in y["cold"].items():
        for ident, v in block.items():
            rows.append(
                [
                    label,
                    f"`{ident}`",
                    (v.get("charged_seconds") or {}).get("n"),
                    _s(_med(v.get("charged_seconds"))),
                    _s(_med(v.get("prepare_seconds"))),
                    _mib(_med(v.get("solve_peak_bytes"))),
                    _mib(_med(v.get("prepare_peak_bytes"))),
                ]
            )
    out += [
        "Cold: a fresh worker per (identity, case), charged = start-up incl. prepare + solve + "
        "transport; peaks from the separate tracemalloc memory pass (MiB); medians over cases.",
        "",
        *_table(
            (
                "cohort / bundle",
                "identity",
                "cases",
                "cold charged p50",
                "cold prepare p50",
                "solve peak p50",
                "prepare peak p50",
            ),
            rows,
        ),
    ]
    return out


def _quote_cli(view: Mapping[str, Any], y: Mapping[str, Any]) -> list[str]:
    attempt = view["attempts"][view["outcome"]["attempt"]]
    walls = [f"`{e['experiment']}` {e['t_end'] - e['t_start']:.1f}" for e in attempt["experiments"]]
    rows = []
    for ident, v in sorted(y["per_identity"].items()):
        times = v["solve_seconds"]
        rows.append(
            [
                f"`{ident}`",
                ", ".join(_s(t) for t in times),
                _s(statistics.median(times)),
                ", ".join(f"{s} {n}" for s, n in sorted(Counter(v["statuses"]).items())),
            ]
        )
    return [
        "### `UQ` (complete-request CLI)",
        "",
        "Five sequential `main.py quote --details --strategies all --profile "
        "config/full_gross.yaml` invocations, USDC → USDT 1000 on the full bundle; each solves "
        "every identity once. CLI wall per invocation (s, process start to exit): "
        + "; ".join(walls)
        + ".",
        "",
        *_table(("identity", "solve s, invocations 1–5", "median", "status"), rows),
    ]


def render(
    raw: Mapping[str, Any], analysis: Mapping[str, Any], ledger: Sequence[Mapping[str, Any]]
) -> str:
    s = analysis["statements"]
    lines = [
        "<!-- GENERATED by `tools/research_024/r024_timing_view.py` from the pinned timing "
        "analysis and ledger; do not edit by hand -->",
        "",
        "# Stage L (`L01-R024`): attempts and the yield of the valid units",
        "",
        f"- (a) measurement attempted correctly: **{s['measurement_attempted_correctly']}**",
        f"- (b) usable latency obtained: **{', '.join(s['usable_latency_obtained']) or 'none'}**",
        "",
        *_attempts(raw, analysis, ledger),
        "## Yield of the valid units (§8.6, descriptive, no verdict)",
        "",
    ]
    for unit in (str(u["unit"]) for u in raw["timing"]["units"]):
        view = analysis["units"][unit]
        y = view.get("yield")
        if y is None:
            continue
        if "per_identity" in y:
            lines += _quote_cli(view, y)
            continue
        for name, part in y.items():
            if name not in ("compare", "overhead_ratio"):
                lines += _measured(name, part)
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="r024_timing_view.py", description=(__doc__ or "").split("\n")[0]
    )
    parser.add_argument("analysis")
    parser.add_argument("ledger")
    parser.add_argument("--out", required=True)
    parser.add_argument("--schedule", default=str(SCHEDULE))
    args = parser.parse_args(argv)
    raw = yaml.safe_load(Path(args.schedule).read_text(encoding="utf-8"))
    analysis = json.loads(Path(args.analysis).read_text(encoding="utf-8"))
    ledger = [
        json.loads(x) for x in Path(args.ledger).read_text(encoding="utf-8").splitlines() if x
    ]
    Path(args.out).write_text(render(raw, analysis, ledger), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
