"""WHI-1633: the C8 search-counter table of a pinned R024 quality analysis, as Markdown.

Presentation only. It reads one committed `*-analysis.json` (written by `r024_campaign.py
analyze`) and renders `rows[*].search_counters`, the per-identity search counters that contract
R024-C/1 §7.4 C8 lists beside the work units. The frozen `tables` renderer
(`r024_campaign_analysis.render_tables`) does not print them. This file was added after stage R
(disclosed in `results.md`). It computes nothing new, decides nothing, and changes no frozen
analysis code. Its output is regenerated byte-identically by
`tests/research_024/test_r024_campaign.py`.

    uv run python tools/research_024/r024_counters.py <analysis.json> --out <counters.md>
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
SCHEDULE = REPO / "config" / "research_024" / "campaign.yaml"
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import r024_campaign_analysis as ca  # noqa: E402


def render(raw: Mapping[str, Any], analysis: Mapping[str, Any]) -> str:
    """One line per arm row (registered order): every counter as `name sum`, with `(n cells)` where
    fewer cells than scheduled carry it (Rule M: a counter a record does not carry is missing)."""
    split = "tuning" if analysis["stage"] == "T" else "report"
    lines = [
        "<!-- GENERATED by `tools/research_024/r024_counters.py` from the pinned analysis; "
        "do not edit by hand -->",
        "",
        f"## C8 — search counters per identity ({split} split, stage {analysis['stage']})",
        "",
        f"Source revision `{analysis['stage_revision']}`. Sums over the row's records; a counter "
        "carried by fewer records than scheduled shows its cell count. Counters of different "
        "identities are different quantities and are never compared across identities.",
        "",
        "| row | scheduled | counters (sum) |",
        "| --- | --- | --- |",
    ]
    for key, row in ca._ordered(raw, analysis["rows"]):
        counters = row.get("search_counters") or {}
        parts = []
        for name, value in sorted(counters.items()):
            text = f"`{name}` {value['sum']:,}"
            if value["cells"] != row["scheduled"]:
                text += f" ({value['cells']} cells)"
            parts.append(text)
        lines.append(f"| `{key}` | {row['scheduled']} | {'; '.join(parts) or '–'} |")
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="r024_counters.py", description=(__doc__ or "").split("\n")[0]
    )
    parser.add_argument("analysis")
    parser.add_argument("--out", required=True)
    parser.add_argument("--schedule", default=str(SCHEDULE))
    args = parser.parse_args(argv)
    raw = yaml.safe_load(Path(args.schedule).read_text(encoding="utf-8"))
    analysis = json.loads(Path(args.analysis).read_text(encoding="utf-8"))
    Path(args.out).write_text(render(raw, analysis), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
